# Link the C runtime statically, so niscord.exe runs on PCs without the
# Visual C++ Redistributable (vcruntime140.dll).
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
