[package]
name = "niscord-protocol"
description = "Messages exchanged between Niscord clients and the signaling server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
